[package]
name = "signaler-launcher"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "signaler"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
anyhow = "1.0.95"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
